[package]
name = "back_to_sequences"
version = "0.2.4"
edition = "2021"


[profile.release]
opt-level = 3               # Use all optimizations.
overflow-checks = false     # Disable integer overflow checks.

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auto_enums = "0.8.2"
clap = { version = "4.4.3", features = ["derive","cargo"] }
which = "5.0.0"
glob = "0.3.0"
fxread = "0.2"
atomic-counter = "1.0.1"
rayon = "1.5.1"


[[bin]]
name = "back_to_sequences"
path = "src/main.rs"