[package]
name = "back_to_sequences"
version = "0.2.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
auto_enums = "0.8.2"
clap = { version = "4.4.3", features = ["derive","cargo"] }
which = "5.0.0"
glob = "0.3.0"
fxread = "0.2"
atomic-counter = "1.0.1"
rayon = "1.5.1"
ctor = "0.2.5"
ahash = "0.8.6"


[[bin]]
name = "back_to_sequences"
path = "src/main.rs"
